#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Announce_HeadshotStreak_5x

#include "Basic.hpp"


namespace SDK::Params
{

// Function Announce_HeadshotStreak_5x.Announce_HeadshotStreak_5x_C.ExecuteUbergraph_Announce_HeadshotStreak_5x
// 0x0004 (0x0004 - 0x0000)
struct Announce_HeadshotStreak_5x_C_ExecuteUbergraph_Announce_HeadshotStreak_5x final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

