#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Announce_BuildingDamaged

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Announce_BuildingDamaged.Announce_BuildingDamaged_C
// 0x0010 (0x0498 - 0x0488)
class AAnnounce_BuildingDamaged_C final : public AFortClientAnnouncement_Basic
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0488(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0490(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Announce_BuildingDamaged(int32 EntryPoint);
	void OnClientAnnouncementStart();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Announce_BuildingDamaged_C">();
	}
	static class AAnnounce_BuildingDamaged_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAnnounce_BuildingDamaged_C>();
	}
};

}

