#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaLockedStyleNotification

#include "Basic.hpp"


namespace SDK::Params
{

// Function AthenaLockedStyleNotification.AthenaLockedStyleNotification_C.ExecuteUbergraph_AthenaLockedStyleNotification
// 0x0004 (0x0004 - 0x0000)
struct AthenaLockedStyleNotification_C_ExecuteUbergraph_AthenaLockedStyleNotification final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function AthenaLockedStyleNotification.AthenaLockedStyleNotification_C.SetLockedStyleDescription
// 0x0018 (0x0018 - 0x0000)
struct AthenaLockedStyleNotification_C_SetLockedStyleDescription final
{
public:
	class FText                                   LockedStyleDescription;                            // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};

}

