#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_PlayerCameraModePullingBlade

#include "Basic.hpp"

#include "Athena_PlayerCameraModeRanged_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Athena_PlayerCameraModePullingBlade.Athena_PlayerCameraModePullingBlade_C
// 0x0000 (0x0C50 - 0x0C50)
class UAthena_PlayerCameraModePullingBlade_C final : public UAthena_PlayerCameraModeRanged_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Athena_PlayerCameraModePullingBlade_C">();
	}
	static class UAthena_PlayerCameraModePullingBlade_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthena_PlayerCameraModePullingBlade_C>();
	}
};

}

