#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_PlayerCameraModeRocket

#include "Basic.hpp"

#include "Athena_PlayerCameraModeRanged_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Athena_PlayerCameraModeRocket.Athena_PlayerCameraModeRocket_C
// 0x0000 (0x0C50 - 0x0C50)
class UAthena_PlayerCameraModeRocket_C final : public UAthena_PlayerCameraModeRanged_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Athena_PlayerCameraModeRocket_C">();
	}
	static class UAthena_PlayerCameraModeRocket_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthena_PlayerCameraModeRocket_C>();
	}
};

}

