#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_DualPistol_Athena

#include "Basic.hpp"

#include "B_Ranged_Dual_Generic_Athena_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_DualPistol_Athena.B_DualPistol_Athena_C
// 0x0010 (0x0E08 - 0x0DF8)
class AB_DualPistol_Athena_C final : public AB_Ranged_Dual_Generic_Athena_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_B_DualPistol_Athena_C;              // 0x0DF8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USoundCue*                              FireSoundOverride;                                 // 0x0E00(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_B_DualPistol_Athena(int32 EntryPoint);
	void OnPlayWeaponFireFX(bool bPersistentFire, bool bSecondaryFire);
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_DualPistol_Athena_C">();
	}
	static class AB_DualPistol_Athena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_DualPistol_Athena_C>();
	}
};

}

