#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BlueprintContext

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class BlueprintContext.BlueprintContextBase
// 0x0000 (0x0028 - 0x0028)
class UBlueprintContextBase : public USubsystem
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"BlueprintContextBase">();
	}
	static class UBlueprintContextBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBlueprintContextBase>();
	}
};

// Class BlueprintContext.BlueprintContextLibrary
// 0x0000 (0x0028 - 0x0028)
class UBlueprintContextLibrary final : public UBlueprintFunctionLibrary
{
public:
	static class USubsystem* GetContext(class UObject* ContextObject, TSubclassOf<class USubsystem> Param_Class);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"BlueprintContextLibrary">();
	}
	static class UBlueprintContextLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBlueprintContextLibrary>();
	}
};

}

