#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BorderMinusSolidBGMinusYellow

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Border-SolidBG-Yellow.Border-SolidBG-Yellow_C
// 0x0000 (0x00B0 - 0x00B0)
class UBorderMinusSolidBGMinusYellow_C final : public UCommonBorderStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Border-SolidBG-Yellow_C">();
	}
	static class UBorderMinusSolidBGMinusYellow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBorderMinusSolidBGMinusYellow_C>();
	}
};

}

