#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BorderMinusShellTopBar

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Border-ShellTopBar.Border-ShellTopBar_C
// 0x0000 (0x00B0 - 0x00B0)
class UBorderMinusShellTopBar_C : public UCommonBorderStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Border-ShellTopBar_C">();
	}
	static class UBorderMinusShellTopBar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBorderMinusShellTopBar_C>();
	}
};

}

