#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PDW

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_PDW.BP_PDW_C.ExecuteUbergraph_BP_PDW
// 0x0004 (0x0004 - 0x0000)
struct BP_PDW_C_ExecuteUbergraph_BP_PDW final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

