#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusTabMinusSecondary

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Tab-Secondary.ButtonStyle-Tab-Secondary_C
// 0x0000 (0x0570 - 0x0570)
class UButtonStyleMinusTabMinusSecondary_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Tab-Secondary_C">();
	}
	static class UButtonStyleMinusTabMinusSecondary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusTabMinusSecondary_C>();
	}
};

}

