#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusOutlineMinusSMinusTransparent

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Outline-S-Transparent.ButtonStyle-Outline-S-Transparent_C
// 0x0000 (0x0570 - 0x0570)
class UButtonStyleMinusOutlineMinusSMinusTransparent_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Outline-S-Transparent_C">();
	}
	static class UButtonStyleMinusOutlineMinusSMinusTransparent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusOutlineMinusSMinusTransparent_C>();
	}
};

}

