#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusQuestMapNode

#include "Basic.hpp"

#include "ButtonStyleMinusMediumBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-QuestMapNode.ButtonStyle-QuestMapNode_C
// 0x0000 (0x0570 - 0x0570)
class UButtonStyleMinusQuestMapNode_C final : public UButtonStyleMinusMediumBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-QuestMapNode_C">();
	}
	static class UButtonStyleMinusQuestMapNode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusQuestMapNode_C>();
	}
};

}

