#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChoiceCardName

#include "Basic.hpp"

#include "CommonUI_classes.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ChoiceCardName.ChoiceCardName_C
// 0x0030 (0x0260 - 0x0230)
class UChoiceCardName_C final : public UCommonUserWidget
{
public:
	class UCommonBorder*                          RarityBG;                                          // 0x0230(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                          RarityBorder;                                      // 0x0238(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       TextName;                                          // 0x0240(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   DisplayText;                                       // 0x0248(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)

public:
	void UpdateText(const class FText& Param_DisplayText, EFortRarity Rarity);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ChoiceCardName_C">();
	}
	static class UChoiceCardName_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChoiceCardName_C>();
	}
};

}

