#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DefaultEditingTool

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DefaultEditingTool.DefaultEditingTool_C
// 0x0000 (0x09B0 - 0x09B0)
class ADefaultEditingTool_C final : public AFortWeap_EditingTool
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DefaultEditingTool_C">();
	}
	static class ADefaultEditingTool_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADefaultEditingTool_C>();
	}
};

}

