#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DefaultUIDataConfiguration

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DefaultUIDataConfiguration.DefaultUIDataConfiguration_C
// 0x0000 (0x31F0 - 0x31F0)
class UDefaultUIDataConfiguration_C final : public UFortUIDataConfiguration
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DefaultUIDataConfiguration_C">();
	}
	static class UDefaultUIDataConfiguration_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDefaultUIDataConfiguration_C>();
	}
};

}

