#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_MED_HIS_Ramirez_Head_01_AnimBP_Child

#include "Basic.hpp"

#include "Fortnite_Base_Head_Export_Skeleton_AnimBP_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass F_MED_HIS_Ramirez_Head_01_AnimBP_Child.F_MED_HIS_Ramirez_Head_01_AnimBP_Child_C
// 0x0000 (0x1190 - 0x1190)
class UF_MED_HIS_Ramirez_Head_01_AnimBP_Child_C final : public UFortnite_Base_Head_Export_Skeleton_AnimBP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"F_MED_HIS_Ramirez_Head_01_AnimBP_Child_C">();
	}
	static class UF_MED_HIS_Ramirez_Head_01_AnimBP_Child_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UF_MED_HIS_Ramirez_Head_01_AnimBP_Child_C>();
	}
};

}

