#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FortniteDefaultBackgroundBlurWidget

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass FortniteDefaultBackgroundBlurWidget.FortniteDefaultBackgroundBlurWidget_C
// 0x0010 (0x0240 - 0x0230)
class UFortniteDefaultBackgroundBlurWidget_C final : public UCommonUserWidget
{
public:
	class UBackgroundBlur*                        BackgroundBlur_0;                                  // 0x0230(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNamedSlot*                             ContentSlot;                                       // 0x0238(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FortniteDefaultBackgroundBlurWidget_C">();
	}
	static class UFortniteDefaultBackgroundBlurWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortniteDefaultBackgroundBlurWidget_C>();
	}
};

}

