#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GAB_AIBaseMelee_NoMontage

#include "Basic.hpp"

#include "GAB_AIBaseMelee_NoMontage_classes.hpp"
#include "GAB_AIBaseMelee_NoMontage_parameters.hpp"


namespace SDK
{

// Function GAB_AIBaseMelee_NoMontage.GAB_AIBaseMelee_NoMontage_C.ExecuteUbergraph_GAB_AIBaseMelee_NoMontage
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGAB_AIBaseMelee_NoMontage_C::ExecuteUbergraph_GAB_AIBaseMelee_NoMontage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GAB_AIBaseMelee_NoMontage_C", "ExecuteUbergraph_GAB_AIBaseMelee_NoMontage");

	Params::GAB_AIBaseMelee_NoMontage_C_ExecuteUbergraph_GAB_AIBaseMelee_NoMontage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GAB_AIBaseMelee_NoMontage.GAB_AIBaseMelee_NoMontage_C.Cancelled_B887396E419FF2C0364C58B63D973822
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayAbilityTargetDataHandle TargetData                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FGameplayTag                     ApplicationTag                                         (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UGAB_AIBaseMelee_NoMontage_C::Cancelled_B887396E419FF2C0364C58B63D973822(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GAB_AIBaseMelee_NoMontage_C", "Cancelled_B887396E419FF2C0364C58B63D973822");

	Params::GAB_AIBaseMelee_NoMontage_C_Cancelled_B887396E419FF2C0364C58B63D973822 Parms{};

	Parms.TargetData = std::move(TargetData);
	Parms.ApplicationTag = std::move(ApplicationTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GAB_AIBaseMelee_NoMontage.GAB_AIBaseMelee_NoMontage_C.Cancelled_DB3662934464473995AE9DABED04B860
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayAbilityTargetDataHandle TargetData                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FGameplayTag                     ApplicationTag                                         (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UGAB_AIBaseMelee_NoMontage_C::Cancelled_DB3662934464473995AE9DABED04B860(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GAB_AIBaseMelee_NoMontage_C", "Cancelled_DB3662934464473995AE9DABED04B860");

	Params::GAB_AIBaseMelee_NoMontage_C_Cancelled_DB3662934464473995AE9DABED04B860 Parms{};

	Parms.TargetData = std::move(TargetData);
	Parms.ApplicationTag = std::move(ApplicationTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GAB_AIBaseMelee_NoMontage.GAB_AIBaseMelee_NoMontage_C.Completed_B887396E419FF2C0364C58B63D973822
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayAbilityTargetDataHandle TargetData                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FGameplayTag                     ApplicationTag                                         (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UGAB_AIBaseMelee_NoMontage_C::Completed_B887396E419FF2C0364C58B63D973822(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GAB_AIBaseMelee_NoMontage_C", "Completed_B887396E419FF2C0364C58B63D973822");

	Params::GAB_AIBaseMelee_NoMontage_C_Completed_B887396E419FF2C0364C58B63D973822 Parms{};

	Parms.TargetData = std::move(TargetData);
	Parms.ApplicationTag = std::move(ApplicationTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GAB_AIBaseMelee_NoMontage.GAB_AIBaseMelee_NoMontage_C.Completed_DB3662934464473995AE9DABED04B860
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayAbilityTargetDataHandle TargetData                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FGameplayTag                     ApplicationTag                                         (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UGAB_AIBaseMelee_NoMontage_C::Completed_DB3662934464473995AE9DABED04B860(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GAB_AIBaseMelee_NoMontage_C", "Completed_DB3662934464473995AE9DABED04B860");

	Params::GAB_AIBaseMelee_NoMontage_C_Completed_DB3662934464473995AE9DABED04B860 Parms{};

	Parms.TargetData = std::move(TargetData);
	Parms.ApplicationTag = std::move(ApplicationTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GAB_AIBaseMelee_NoMontage.GAB_AIBaseMelee_NoMontage_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGAB_AIBaseMelee_NoMontage_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GAB_AIBaseMelee_NoMontage_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GAB_AIBaseMelee_NoMontage.GAB_AIBaseMelee_NoMontage_C.Triggered_B887396E419FF2C0364C58B63D973822
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayAbilityTargetDataHandle TargetData                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FGameplayTag                     ApplicationTag                                         (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UGAB_AIBaseMelee_NoMontage_C::Triggered_B887396E419FF2C0364C58B63D973822(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GAB_AIBaseMelee_NoMontage_C", "Triggered_B887396E419FF2C0364C58B63D973822");

	Params::GAB_AIBaseMelee_NoMontage_C_Triggered_B887396E419FF2C0364C58B63D973822 Parms{};

	Parms.TargetData = std::move(TargetData);
	Parms.ApplicationTag = std::move(ApplicationTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GAB_AIBaseMelee_NoMontage.GAB_AIBaseMelee_NoMontage_C.Triggered_DB3662934464473995AE9DABED04B860
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayAbilityTargetDataHandle TargetData                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FGameplayTag                     ApplicationTag                                         (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UGAB_AIBaseMelee_NoMontage_C::Triggered_DB3662934464473995AE9DABED04B860(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GAB_AIBaseMelee_NoMontage_C", "Triggered_DB3662934464473995AE9DABED04B860");

	Params::GAB_AIBaseMelee_NoMontage_C_Triggered_DB3662934464473995AE9DABED04B860 Parms{};

	Parms.TargetData = std::move(TargetData);
	Parms.ApplicationTag = std::move(ApplicationTag);

	UObject::ProcessEvent(Func, &Parms);
}

}

