#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_RiftSpawnerPreCreate

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_RiftSpawnerPreCreate.GCN_RiftSpawnerPreCreate_C
// 0x0000 (0x01A0 - 0x01A0)
class UGCN_RiftSpawnerPreCreate_C final : public UFortGameplayCueNotify_Burst
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_RiftSpawnerPreCreate_C">();
	}
	static class UGCN_RiftSpawnerPreCreate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_RiftSpawnerPreCreate_C>();
	}
};

}

