#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_GM_Heal

#include "Basic.hpp"

#include "GET_Heal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_GM_Heal.GE_GM_Heal_C
// 0x0000 (0x05F0 - 0x05F0)
class UGE_GM_Heal_C final : public UGET_Heal_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_GM_Heal_C">();
	}
	static class UGE_GM_Heal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_GM_Heal_C>();
	}
};

}

