#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_StunActive_0

#include "Basic.hpp"

#include "GET_TagContainer_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_StunActive.GE_StunActive_C
// 0x0000 (0x05F0 - 0x05F0)
class GE_StunActive_0::UGE_StunActive_C final : public UGET_TagContainer_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BlueprintGeneratedClass GE_StunActive.GE_StunActive_C", true, "GE_StunActive_C">();
	}
	static class GE_StunActive_0::UGE_StunActive_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<GE_StunActive_0::UGE_StunActive_C>();
	}
};

}

