#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GiftingUserItemSmall

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass GiftingUserItemSmall.GiftingUserItemSmall_C
// 0x0008 (0x0B48 - 0x0B40)
class UGiftingUserItemSmall_C final : public UFortGiftingUserItem
{
public:
	class UWidgetAnimation*                       Toggle;                                            // 0x0B40(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GiftingUserItemSmall_C">();
	}
	static class UGiftingUserItemSmall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGiftingUserItemSmall_C>();
	}
};

}

