#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemReceivedDeepFreezeBundleHeader

#include "Basic.hpp"

#include "ItemReceivedDeepFreezeBundleHeader_classes.hpp"
#include "ItemReceivedDeepFreezeBundleHeader_parameters.hpp"


namespace SDK
{

// Function ItemReceivedDeepFreezeBundleHeader.ItemReceivedDeepFreezeBundleHeader_C.ExecuteUbergraph_ItemReceivedDeepFreezeBundleHeader
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UItemReceivedDeepFreezeBundleHeader_C::ExecuteUbergraph_ItemReceivedDeepFreezeBundleHeader(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemReceivedDeepFreezeBundleHeader_C", "ExecuteUbergraph_ItemReceivedDeepFreezeBundleHeader");

	Params::ItemReceivedDeepFreezeBundleHeader_C_ExecuteUbergraph_ItemReceivedDeepFreezeBundleHeader Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemReceivedDeepFreezeBundleHeader.ItemReceivedDeepFreezeBundleHeader_C.BndEvt__CandleLightButton_K2Node_ComponentBoundEvent_61_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButton*                    Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UItemReceivedDeepFreezeBundleHeader_C::BndEvt__CandleLightButton_K2Node_ComponentBoundEvent_61_CommonButtonClicked__DelegateSignature(class UCommonButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemReceivedDeepFreezeBundleHeader_C", "BndEvt__CandleLightButton_K2Node_ComponentBoundEvent_61_CommonButtonClicked__DelegateSignature");

	Params::ItemReceivedDeepFreezeBundleHeader_C_BndEvt__CandleLightButton_K2Node_ComponentBoundEvent_61_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemReceivedDeepFreezeBundleHeader.ItemReceivedDeepFreezeBundleHeader_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UItemReceivedDeepFreezeBundleHeader_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemReceivedDeepFreezeBundleHeader_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

