#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemReceivedGenericRewardHeader

#include "Basic.hpp"

#include "ItemReceivedGenericRewardHeader_classes.hpp"
#include "ItemReceivedGenericRewardHeader_parameters.hpp"


namespace SDK
{

// Function ItemReceivedGenericRewardHeader.ItemReceivedGenericRewardHeader_C.ExecuteUbergraph_ItemReceivedGenericRewardHeader
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UItemReceivedGenericRewardHeader_C::ExecuteUbergraph_ItemReceivedGenericRewardHeader(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemReceivedGenericRewardHeader_C", "ExecuteUbergraph_ItemReceivedGenericRewardHeader");

	Params::ItemReceivedGenericRewardHeader_C_ExecuteUbergraph_ItemReceivedGenericRewardHeader Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemReceivedGenericRewardHeader.ItemReceivedGenericRewardHeader_C.InitFromGiftBoxItem_BP
// (Public, BlueprintCallable, BlueprintEvent)

void UItemReceivedGenericRewardHeader_C::InitFromGiftBoxItem_BP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemReceivedGenericRewardHeader_C", "InitFromGiftBoxItem_BP");

	UObject::ProcessEvent(Func, nullptr);
}

}

