#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MissionGen_Ground

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MissionGen_Ground.MissionGen_Ground_C
// 0x0000 (0x06C0 - 0x06C0)
class UMissionGen_Ground_C final : public UFortMissionGenerator
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MissionGen_Ground_C">();
	}
	static class UMissionGen_Ground_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMissionGen_Ground_C>();
	}
};

}

