#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPCLeaderItemPedestal

#include "Basic.hpp"

#include "NPCLeaderItemPedestal_classes.hpp"
#include "NPCLeaderItemPedestal_parameters.hpp"


namespace SDK
{

// Function NPCLeaderItemPedestal.NPCLeaderItemPedestal_C.ExecuteUbergraph_NPCLeaderItemPedestal
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPCLeaderItemPedestal_C::ExecuteUbergraph_NPCLeaderItemPedestal(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPCLeaderItemPedestal_C", "ExecuteUbergraph_NPCLeaderItemPedestal");

	Params::NPCLeaderItemPedestal_C_ExecuteUbergraph_NPCLeaderItemPedestal Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPCLeaderItemPedestal.NPCLeaderItemPedestal_C.CameraChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EFrontEndCamera                         NewCamera                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFrontEndCamera                         OldCamera                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPCLeaderItemPedestal_C::CameraChanged(EFrontEndCamera NewCamera, EFrontEndCamera OldCamera)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPCLeaderItemPedestal_C", "CameraChanged");

	Params::NPCLeaderItemPedestal_C_CameraChanged Parms{};

	Parms.NewCamera = NewCamera;
	Parms.OldCamera = OldCamera;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPCLeaderItemPedestal.NPCLeaderItemPedestal_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ANPCLeaderItemPedestal_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPCLeaderItemPedestal_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NPCLeaderItemPedestal.NPCLeaderItemPedestal_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ANPCLeaderItemPedestal_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPCLeaderItemPedestal_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

