#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PBWA_W1_StairSpiral

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PBWA_W1_StairSpiral.PBWA_W1_StairSpiral_C
// 0x0000 (0x0C98 - 0x0C98)
class APBWA_W1_StairSpiral_C final : public ABuildingStairs
{
public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PBWA_W1_StairSpiral_C">();
	}
	static class APBWA_W1_StairSpiral_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APBWA_W1_StairSpiral_C>();
	}
};

}

