#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerReportingCategoryDropdown

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass PlayerReportingCategoryDropdown.PlayerReportingCategoryDropdown_C
// 0x0010 (0x0360 - 0x0350)
class UPlayerReportingCategoryDropdown_C final : public UFortDropdownMenu
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0350(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UVerticalBox*                           MainButtonVerticalBox;                             // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_PlayerReportingCategoryDropdown(int32 EntryPoint);
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PlayerReportingCategoryDropdown_C">();
	}
	static class UPlayerReportingCategoryDropdown_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlayerReportingCategoryDropdown_C>();
	}
};

}

