#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Recreation_SportingGoods_Basketball

#include "Basic.hpp"

#include "PhysicsBall_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Recreation_SportingGoods_Basketball.Recreation_SportingGoods_Basketball_C
// 0x0000 (0x08A0 - 0x08A0)
class ARecreation_SportingGoods_Basketball_C final : public APhysicsBall_Master_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Recreation_SportingGoods_Basketball_C">();
	}
	static class ARecreation_SportingGoods_Basketball_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ARecreation_SportingGoods_Basketball_C>();
	}
};

}

