#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: STW_PlayerCameraModeRanged

#include "Basic.hpp"

#include "Athena_PlayerCameraModeRanged_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass STW_PlayerCameraModeRanged.STW_PlayerCameraModeRanged_C
// 0x0000 (0x0C50 - 0x0C50)
class USTW_PlayerCameraModeRanged_C final : public UAthena_PlayerCameraModeRanged_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"STW_PlayerCameraModeRanged_C">();
	}
	static class USTW_PlayerCameraModeRanged_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USTW_PlayerCameraModeRanged_C>();
	}
};

}

