#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TeamID_PvP_22

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TeamID_PvP_22.TeamID_PvP_22_C
// 0x0000 (0x0038 - 0x0038)
class UTeamID_PvP_22_C final : public UFortTeamIdentification
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TeamID_PvP_22_C">();
	}
	static class UTeamID_PvP_22_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTeamID_PvP_22_C>();
	}
};

}

