#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusBaseMinusXSMinusYellow

#include "Basic.hpp"

#include "TextStyleMinusBaseParent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Base-XS-Yellow.TextStyle-Base-XS-Yellow_C
// 0x0000 (0x0148 - 0x0148)
class UTextStyleMinusBaseMinusXSMinusYellow_C final : public UTextStyleMinusBaseParent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Base-XS-Yellow_C">();
	}
	static class UTextStyleMinusBaseMinusXSMinusYellow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusBaseMinusXSMinusYellow_C>();
	}
};

}

