#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusBaseMinusSMinusBMinus60pc

#include "Basic.hpp"

#include "TextStyleMinusBaseMinusS_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Base-S-B-60pc.TextStyle-Base-S-B-60pc_C
// 0x0000 (0x0148 - 0x0148)
class UTextStyleMinusBaseMinusSMinusBMinus60pc_C final : public UTextStyleMinusBaseMinusS_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Base-S-B-60pc_C">();
	}
	static class UTextStyleMinusBaseMinusSMinusBMinus60pc_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusBaseMinusSMinusBMinus60pc_C>();
	}
};

}

